// <auto-generated />
namespace StormCrow.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class IoC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IoC));
        
        string IMigrationMetadata.Id
        {
            get { return "201411070945071_IoC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
