// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace StormCrow.Web.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class NameChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201410050344404_NameChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
